# .github/workflows/release.yml

on:
  release:
    types: [created]

jobs:
  release-linux-amd64:
    name: release linux/amd64
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: serafdev/go-release-action@v1.37-alpha.1
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        goos: linux
        goarch: amd64
        release_repo: serafdev/go-release-action-test-public
        goversion: "https://go.dev/dl/go1.20.linux-amd64.tar.gz"
        project_path: "."
        binary_name: "go-release-action-test-private"
        release_tag:  "v0.0.1-alpha.1"
